apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: datalake
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    parameters:
      compression_mode: none
  preservePoolsOnDelete: false
  gateway:
    port: 80
    instances: 3
