apiVersion: v1
kind: Pod
metadata:
  name: debian-deployment
  namespace: default
spec:
  containers:
    - name: debian
      image: debian:latest
      command: ['sleep', 'infinity']
      env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quickstart-es-elastic-user
              key: elastic
      resources:
        limits:
          memory: '100Gi'
          cpu: '60'
        requests:
          memory: '20Gi'
          cpu: '1'
      volumeMounts:
        - mountPath: /mnt/data
          name: debian-storage
  volumes:
    - name: debian-storage
      persistentVolumeClaim:
        claimName: debian-pvc
